[package]
name = "learn-rust-wasm"
version = "0.1.0"
authors = ["Victor Lee <victorlee228@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1.1", optional = true }